### ISSUE TITLE
DCPU doesn't work

### ISSUE THREAD

**Issue by Razboinicul** [atirut-w/dcpu16-emu#1]
I tried to load the example code and I got errors every step saying: Unknown special opcode: 0x0

**Comment by atirutw** [comment]
This is because I have not implemented it(special opcode 0), and it will probably stay that way since [it is a reserved special opcode in the specifications](https://gist.github.com/metaphox/3888117#file-dcpu-16spec-txt-L129).

**Comment by Razboinicul** [comment]
ok
